### ISSUE TITLE
Size of swipe under finger is too wide.

### ISSUE THREAD

**Issue by pashakubov** [donaldrshade/bible-word-find-kriol#32]
The swipe under the finger does not create a problem on the smaller 3 x3 and 4 x 4 grids, but it definitely creates a problem on the larger 7 x 7 to 10 x 10 grids.
It would be good to make the highlighted swipe the width of the letters, not the width of the finger.

**Comment by pashakubov** [comment]
While playing around in puzzle 33 ("Jisas bin stapes win en web", audio, 10 x 10 grid, 12 words), some of the words select, others do not. I used bread points to reveal letters, this worked ok, but still some words that were obviously there even with revealed letters, would not select. This could be connected to the size of the finger swipe and the size of the letters, I don't know. (Or it could be another problem- I hope not.)

**Comment by pashakubov** [comment]
![IMG_0308](https://user-images.githubusercontent.com/61955423/76580027-eb065200-6515-11ea-8979-60c898139bc7.jpeg)

**Comment by davidmstirn** [comment]
Fixed in 2cab2693c6905af9bad76133d65a04e5084cae78
