### ISSUE TITLE
After completing puzzle 4, the game directs to audio puzzle 33.

### ISSUE THREAD

**Issue by pashakubov** [donaldrshade/bible-word-find-kriol#34]
This may be another database problem.
Once I have started playing the game now, and progressing through the puzzles and levels, the database redirects to puzzle 33 after every completed puzzle.

**Comment by davidmstirn** [comment]
Fixed in 4c43072d9f07dfa2b4376bba8827c9c1dcdc0232 . Now tapping the check takes you to the next level
