### ISSUE TITLE
** (Fix at end of testing.) Locking system needed for Geim Lebul screen.

### ISSUE THREAD

**Issue by pashakubov** [donaldrshade/bible-word-find-kriol#40]
This will have to be one of the last things implemented, because it is handy to have all of the levels open for testing.
Once testing is completed, a locking system will be needed so that levels can only be played once they are unlocked.
A good way to do this may be to have locked levels greyed out, and unlocked levels in full black.

**Comment by davidmstirn** [comment]
Added during codeathon.
